### ISSUE TITLE
Manhattan plot par paires de populations

### ISSUE THREAD

**Issue by Doniol-Valcroze** [BELKHIR/shinyvcfanalyser#6]
Bonjour Khalid,

Il pourrait être intéressant de pouvoir sélectionner 2 populations dans notre jeu de donnée et d'obtenir un manhattan plot basé seulement sur le FST entre ces 2 populations.

Merci d'avance,

Paul

**Comment by BELKHIR** [comment]
Bonjour Paul,

This change have been committed.

Khalid,
